### ISSUE TITLE
Token reward URL's should be shorter

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#11]
- [x] Remove the current logic to generate a hash
- [x] This should be the new reward claim URL:
```
https://dev-wallet.thx.network/claim?hash=eyJjaGFpbklkIjoxMzcsInBv....
https://dev-wallet.thx.network/claim/<claim_id>
```
- [x] QR code should be generated for this URL
