### ISSUE TITLE
As a dashboard user I want to receive a weekly pool analytics report

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#114]
I would love to make some progress on this, since it could also be a good vehicle to drive engagement with our own product.

Things we could show:
- Claimed total amount of points claimed for the pool sum(referral + conditional + milestones)
- Top 5 of users based on claimed points all time
- Total amount of both erc20 and erc721 perks claimed 

API
- [ ] Create a job that runs on a weekly basis and calculates the above
- [ ] Reuse MetricsService created for dashboard analytics
- [ ] Add sections for every pool in the email
- [ ] Send an email when the job finishes (weekly Monday 9am)
