### ISSUE TITLE
As a user I want to receive reminders on pending actions

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#115]
Pending actions could be:

- [ ] A job that on a daily basis at 9am scans for the the conditions below and sends emails.

**Account created but no Tokens or Collectibles (Email with tips on how to deploy assets)**
- [ ] Query auth for req.auth.sub to get account.email
- [ ] Query erc20.sub to see if there is anything created
- [ ] Query erc721.sub to see if there is anything created
- [ ] If nothing has been created 7 days after signup, send the email

- Account and tokens / collectibles created but no pools to start using features (Email with tips on how to config pool)
- [ ] Query auth for req.auth.sub to get account.email
- [ ] Query erc20.sub to see if there is anything created
- [ ] Query erc721.sub to see if there is anything created
- [ ] If something has been created but no pool, send the email.

- Pool created for tokens / collectibles but no withdrawals for that pool (Email with tips on how to config rewards etc)
- [ ] Query auth for req.auth.sub to get account.email
- [ ] Query for pool.sub to see if there is anyhthing created
- [ ] Query for withdrawals.poolId to see if there is anything created
- [ ] If no withdrawals have been created, send the email.
