### ISSUE TITLE
Extend auth with claims:write and claims:read scopes and process claim_id or reward_hash correctly

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#13]
Auth
- [x] Introduce `claims:write`, `claims:read` scopes in oidc config
- [x] Extend THX Auth client with `claims:write`, `claims:read` scopes
- [x] Extend requested scopes in api.ts util with `claims:read`
- [x] Change oidc/:uid/claim controller to process reward_hash if available
- [ ] Change oidc/:uid/claim controller to process claim_id if available and use apiClient util
- [x] Introduce ClaimProxy in project (like BrandProxy)
