### ISSUE TITLE
As a wallet user I want a smart contract wallet after a signin

### ISSUE THREAD

**Issue by ghost** [thxprotocol/monorepo-legacy#130]
As a wallet user I want a smart contract wallet after a signin
    1. If account.walletAddress is not set deploy the shared wallet
    2. Read receipt.address and set account.walletAddress with it and keep account.address as is

API
 - [ ] Add "wallets" resource in the API
 - [ ] Add post controller to create Wallet object in "wallets" collection
 - [ ] Also deploy the wallet contract with this controller (and add relayer as default owner)
 - [ ] Add list controller to return list of wallet objects
 - [ ] Add tests

Auth
 - [ ] In auth create a WalletProxy 
 - [ ] In WalletProxy add create method to trigger the POST
 - [ ] In WalletProxy add list method to fetch all wallets for a sub
 - [ ] After account sign list all wallets for a sub and if wallets.length > 0 and if not then use WalletProxy to create wallet

**Comment by peterpolman** [comment]
I have moved the SharedWallet into SharedWalletFacet and made it an upgradeable diamond variant. Integrated this in API as well and made sure your tests are passing.
