### ISSUE TITLE
As an SDK user I want to only interact with the API

### ISSUE THREAD

**Issue by ghost** [thxprotocol/monorepo-legacy#132]
API
- [ ] Introduce erc20transfer resource (post, list, get) to controller root level

SDK
- [ ] Extend erc20 service with transfer method 
- [ ] Implement transfer(from, to, amount) method to call API
- [ ] Remove torus and web3 dependencies from the sdk
