### ISSUE TITLE
As a shared wallet user I want to be able to manage access

### ISSUE THREAD

**Issue by ghost** [thxprotocol/monorepo-legacy#134]
Solidity
- [x] Implement AccessControl
- [x] Add MANAGER role
- [x] In constructor of SharedWallet also give owner the role
- [x] Add `onlyManager` on the transferERC20 function
- [x] Create tests to grant and revoke role and transfer funds
- [x] Make sure grantRole and revokeRole are only accessible by roleAdmin

API
- [x] Add resource `/wallets/:id/managers/` (get, list, delete) with collection `walletManagers`
- [x] Add tests

Wallet
- [x] Add "Access Control" item to Wallet dropdown
- [x] Open modal with list of whitelisted addresses (GET /wallet/:id/managers)
- [ ] Add field for adding a wallet address and POST /wallet/:id/managers)
- [ ] Update the list
- [ ] Next to every item in the list add a remove icon and call (DELETE /wallet/:id/managers/:id)
- [ ] Limit the amount of managers for a SharedWallet to 3
