### ISSUE TITLE
Introduce claims resource

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#14]
Model:
```
type Claim = {
    _id: string,
    poolId:string,
    erc20Id: string,
    erc721Id:string,
    rewardId: string,
}
```

- [x] Change POST /rewards controller to insert a new Claim object (do this in RewardService.create)
- [x] Introduce `claim` resource and router
- [x] Introduce GET controller and respond with Claim data from db
```
chainId
poolAddress
tokenSymbol
rewardId
rewardAmount
rewardCondition
clientId
```
- [x] Router should be guarded with rewardclaim scopes
- [x] Extend the reward tests with checks for `reward.claimId`

**Comment by ghost** [comment]
return the composed information in the get controller based on claimId
