### ISSUE TITLE
Create upgradeable SharedWallet contract

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#140]
```
SharedWallet extends OpenZeppelinUpgradeProxy {
    approveERC20(_tokenAddress address, _address address, _amount uint);
    transferERC20(_tokenAddress address, _to address, _amount uint);
    changeOwnershipERC721(_tokenAddress address, _newOwner address, _tokenId uint);
}
```
- [ ] Introduce new module "wallet" in solidity repo
- [ ] Extend from OZ upgrade proxy contract
- [ ] Implement/proxy basic ERC721 and ERC20 features
- [ ] Create tests for those features
- [ ] Make sure to export abi and bytecode so you can use it for development in the API
