### ISSUE TITLE
Create widget injection script

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#170]
- [ ] Add new entrypoint in wallet app that builds at this location `https://wallet.thx.network/inject.js`
- [ ] Make sure we can provide script that is executed on the page where it is loaded (self invoking)
- [ ] Let the script build a button with a `thx-` prefixed class (to make sure it does not receive styles from the site where it is loaded in
- [ ] Add event listener on button and open widget
- [ ] The widget should be an iframe that loads our wallet
