### ISSUE TITLE
As a dashboard user I want to create and list referral rewards

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#174]
API

- [x] create the type RewardReferral

 ```
type RewardReferral extends TBaseReward {
    amount: number;
    successUrl: string;
}
```

- [x] Introduce ReferralReward model in database
- [x] Introduce POST /referral-rewards endpoint
- [x] Introduce GET /referral-rewards endpoint
- [x] Add validation for the endpoint
- [x] Add ReferralReward tests suite

Auth:
- [x] Add scopes for `referral_rewards:read`, `referral_rewards:write`

Dashboard:
- [x] Add sidebar menu item "Referral Rewards"
- [x] Copy view template from ERC20Rewards
- [x] Open model for "Create Referral Reward" button
- [x] In model provide form for `amount`, `title`, `description`.
- [x] On submit call POST /referral-rewards
- [x] Update list with referral-rewards
