### ISSUE TITLE
As a referrer I want to see Web Widget in an iFrame

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#175]
- [ ] Introduce new vue3 "widget" app in monorepo
- [x] Prepare amplify to deploy to (dev-)widget.thx.network
- [x] Introduce pinea as data store
- [x] Make sure bootstrap vue works properly in widget app
- [x] Implement THX SDK for all THX API communication
- [x] Introduce storybook for our low level vue3 web components (buttons, form elements, alerts etc -> atoms)
