### ISSUE TITLE
As a referrer I want to see a list of point rewards

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#177]
API 
- [ ] Introduce new resource `PointRewards`
- [ ] Add list controller that aggregates all reward types
- [ ] Respond with data in format easily consumable by widget

Auth
- [ ] Introduce scopes `point_reward:read` `point_reward:write`

SDK
- [ ] Introduce PointRewardsManager and expose `list()` method

Widget
- [ ] Introduce /rewards route
- [ ] Call GET /points-rewards/list
- [ ] Display a card per PointReward
