### ISSUE TITLE
As a referrer I want to see my referral URL

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#178]
Flow: 
Alice requests her referral URL: `https://xyz.com/?referral=<guid>`
Alice send Bob her referral URL
Bob visits xyz.com (not authenticated)
SDK reads `?referral` from search params into `referralUuid`

Dev tasks
- [ ] GET /point-rewards should not return Claims when not authenticated
- [ ] GET /point-rewards should return Claim for query { sub, referralRewardId} if it exists
- [ ] If Claim for sub and referralRewardId does not exist create it and add the Claim to the response
- [ ] Extend test suite for point rewards

**Comment by peterpolman** [comment]
@valeriagrazzini Revisiting this and wondering how we are going to store sub + guid for the ReferralReward. We can't store them in the same collection since these are made from the dashboard with the sub of the creator.

I guess we need to introduce a new collection like ReferralRewardClaim. These are created when the widget user presses "Claim reward" and should at least contain smth like this
```
type ReferralRewardSub {
    referralRewardId: string;
    sub: string;
    uuid: string;
}
```

Perhaps we can also just start tracking state here with a `state` property. Probably best to start doing this for all claims...

**Comment by ghost** [comment]
@peterpolman it is not clear here "GET /point-rewards should return Claim for query { sub, referralRewardId} if it exists" :
where do I get the referralRewardId from?
It could be: "GET /point-rewards/: referralUuid ", or perhaps we pass the value in the query string?
