### ISSUE TITLE
Add descriptions to RewardBase model

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#206]
- [x] Add `description` field in dashboard reward create models
- [x] Extend reward validation with optional description field
- [x] Store description in db
- [x] Return description on the GET endpoints for the rewards
- [x] Display the description in the CardReward in dashboard
