### ISSUE TITLE
Export QR codes to PDF

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#210]
- [x] Change default export format of QR codes to "pdf"
- [x] Make sure brand logo images are still part of the created QR code (assuming we can not "vectorize" this bitmap data)
- [x] Run tests on individual and bulk QR code creation
