### ISSUE TITLE
As a user I want to download a zip file with multiple (unique) QR codes for claims on a specific reward

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#22]
CardReward:
- [x] Instead of showing the QR code for the reward object as we do now, show the QR code for the claim URL (`https://wallet.thx.network/claim/<claimId>`)
- [x] When `reward.claimIds > 1` there are multiple QR codes possible, in this case present a "Download QR codes" button in the UI and hide the URL input field.
- [ ] When clicking "Download" call `GET /rewards/:id/claims/qrcode` and see that a zip file is being downloaded.

ModalRewardCreate:
- [x] Provide `input[type="number"]` to modal
- [x] Add `amount` property to POST /rewards request (different than the current `withdrawAmount` or `supply`)
- [x] Default value for amount should be `1`
