### ISSUE TITLE
Add endpoint to download zip file with QR code images

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#23]
- [x] Extend Reward modal with `amount` property
- [x] Create migration to set `amount` for all the already existing rewards to 1
- [x] Extend `GET /reward` endpoint response with a list of claimId's (`claims: string[]`) when `reward.amount > 1`
- [x] Add `GET /rewards/:id/claims/qrcode` endpoint
- [x] In the controller query for all claims for rewardId `req.params.id`
- [x] Create QR code images for all claims (and write to disk? or do this in memory)
- [x] Zip all the individual images and remove temporary storage
- [x] Test with 5000 - 10000 claims and see how it performs
- [x] Probably create a job if the requests takes long and send an email with download link when done.

**Comment by ghost** [comment]
This is completed.
The only thing I am not able to test is the email sending @peterpolman
