### ISSUE TITLE
As a dashboard user I want to create Lottery Perk

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#286]
API (LotteryPerk)
- [ ] Add ERC721.variant property for enum value
- [ ] Extend ERC721Variant enum with "Lottery"
- [ ] Create LotteryPerk resource CRUD
- [ ] In POST controller also create an ERC721 object and deploy contract (do not await)
- [ ] In POST controller also set erc721.variant with ERC721Variant.Lottery
- [ ] Update the `LotteryPerk.erc721Id` with the `ERC721._id`
- [ ] In POST controller also create `ERC721Metadata` for the ERC721 object
- [ ] Populate `ERC721Metadata` properties with the values submitted in the body

API (Lottery Agenda Job)
- [ ] Create model LotteryPerkWinner with properties { erc721Id, lotteryPerkId, sub, prizeAmount, createdAt }
- [ ] Create Agenda job that runs every day at 06:00
- [ ] Query for all the LotteryPerks where `now > perk.startDate` and  if `perk.endDate` is defined `now < perk.endDate`
- [ ] Iterate over the results and query the `ERC721Token` objects for the `perk.erc721Id`
- [ ] Calculate `perk.prizes.length` amount of random ints between 0 and the ERC721Token found for the `perk.erc721Id`.
- [ ] Select the tokens that won based on the random ints and get account info for `ERC721Token.sub`
- [ ] Get prize receiving address with `account.getAddress(erc721.chainId)` and transfer the prize amount from the pool to that address
- [ ] Send emails to the e-mail addresses for the accounts (if any)
- [ ] Create LotteryPerkWinner for every sub

Dashboard
- [ ] Create Lottery Perk navbar item and overview
- [ ] Create LotteryPerk modal with fields: pointPrice, title, description, image, prizes (`number[]`), periodInDays (number), erc20Id (dropdown component), startDate: Date, endDate: Date (optional), infoUrl: string.

![Image](https://user-images.githubusercontent.com/2378695/208501551-a7dc3bea-3f0e-4cb5-a9e1-55b449491447.png)

**Comment by peterpolman** [comment]
Perhaps better to call this the (potentially random and limited) Airdrop Perk.
