### ISSUE TITLE
As a dashboard user I want to see a list of referral claims

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#291]
API
- [x] Add GET /v1/referral-rewards/:uuid/claims and return list of claims for that referral reward
- [x] Also add user information {firstName, lastName, email } based on ReferralRewardClaim.sub in the response

Dashboard
- [x] Add modal with table for ReferralRewardClaims on referral overview and list claims for specific referral reward
- [x] By default sort isApproved !== true claims on top and then sort on createdAt

**Comment by ghost** [comment]
@peterpolman firstName, lastName info are not registered on the account table, so I put only the email

**Comment by peterpolman** [comment]
These fields are available in the database and can be updated on a users
account page. The fixture doesn’t contain data for it though, so that might
be confusing. I’d suggest to check if the account proxy in API returns the
values once you set them and also provide UI for it in the claims table.

**Comment by ghost** [comment]
thank you, I added them to the table
