### ISSUE TITLE
As a dashboard user I want to approve referral claims

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#292]
Dashboard
- [x] In ReferralRewardClaim overview add button "Approve"
- [x] On click call `PATCH /referral-rewards/:uuid/claims` with array of claimUuids

API
- [x] Add `PATCH /v1/referral-rewards/:uuid/claims` controller
- [x] Transfer ReferralReward.amount points to the ReferralRewardClaim.sub users in the job

**Comment by ghost** [comment]
these sub tasks are implemented in the branch: origin/referral-claims
