### ISSUE TITLE
As a dashboard user I want to see charts for claims and referral reward claims

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#303]
Rewards
- [ ] Show the sum of all kinds of point rewards over time in the chart
- [ ] Use the last day for the metrics cards below the chart

Perks
- [ ] Show the count of all kinds of perks over time in the chart for a day
- [ ] Return specific metrics for the sum of all perks in total 
- [ ] If the visualisation is hard to achieve lets discuss an alternative from examples available

Leaderboard
- [ ] Add table card to dashboard to list "top 5" users
- [ ] Get all ReferralClaim, MilestoneClaim, PointClaim for pool
- [ ] Group by sub and take sum of amounts 
- [ ] Sort the result based on amount desc
- [ ] Limit to 5 results
- [ ] Get the accounts for the balance subs

![Image](https://user-images.githubusercontent.com/2378695/210567807-cccfc519-a713-4869-9756-6a05b1c1b695.png)
