### ISSUE TITLE
As a backend I want to call a webhook to mark referrals as qualified

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#308]
**Dashboard**
- [ ] Rename "Referral Completion" "URL Qualification"
- [ ] Add "Webhook Qualification"  in Referral reward edit modal
- [ ] Show this code in code box 
```
curl "https://api.thx.network.com/v1/webhook/{referral.token}/qualify" \
    -X POST \
    -d "code={code}"
```

**API**
- [ ] Extend ReferralReward with `token` property which is another uuid
- [ ] Add `POST /v1/webhook/referral/:token/qualify` with body.code
- [ ] In controller create ReferralRewardClaim for the referral related to the token and the user related to the code

**Comment by peterpolman** [comment]
@valeriagrazzini PR is still in draft, is that correct or is it ready for review? (tests are also failing after merging in the latest develop test fixes)

**Comment by ghost** [comment]
Only the migration for the token is missing
