### ISSUE TITLE
As a widget user I want to share multiple referral URL's

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#309]
Widget
- [x] Create hash for `account.sub` and `referralReward.uuid`
- [x] Use hash as ?ref= param in referral URL
- [x] Pass hash into iframe and widget storage
- [x] Get referral for uuid
- [x] Pass back successUrls to parent window object
- [x] Start listening for successUrl(s) for referral
 
API
- [x] Remove findOne for referral in pool
