### ISSUE TITLE
As a dashboard user I want to create a Milestone Reward

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#313]
**Dashboard**
- [x] Create new pool child page for path `/pool/:id/milestones` (follow patterns on other pages!)
- [x] Show b-table with milestone rewards
- [x] Add MilestoneRewardCreate modal with fields: `Title`, `Description`, `Amount`
- [x] Create a more generic component for the webhook UI part of the ReferralRewardCreate form and also implement for this modal (see these lines https://github.com/thxprotocol/monorepo/pull/310/files#diff-ceef06726d01f5b99d7053acf5eadb107cb1b3e8b28eb0d8da35deb45d45c60fR4-R22)
- [x] Webhook URL for this reward should be `POST /v1/webhook/milestones/:token/claim`

**API**
- [x] Add milestones resource with controllers for POST, LIST, GET, PATCH, DELETE
- [x] Extend webhooks resource with milestones subfolder and claim route

**Comment by peterpolman** [comment]
@GarfDev When users claim the `MilestoneReward` should create a `MilestoneRewardClaim` object through the claims/collect endpoint or the `POST rewards/milestones/uuid/claim` as per used endpoints for reward claims in the widget.
