### ISSUE TITLE
As a widget user I want to transfer tokens

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#323]
API
- [x] Use existing erc20/transfer POST controllers for widget erc20 transfer
- [x] Validate for erc20Id, to, amount
- [x] Derive chainId from erc20
- [x] Derive from address from authenticated user
- [x] Make sure to create ERC20Transfer object 
- [x] Make sure to use the callback pattern so we can pool for tx updates
- [x] Make sure to list transfers based on erc20Id
- [x] Make sure to read a specific transfer based on erc20TransferId and also return the transaction object

Widget
- [x] Make ERC20Card in widget collapsible
- [x] Provide number input for transfer amount
- [x] Provide text input (with address validation) for transfer to address
- [x] Create request for ERC20 transfer from the users smart contract wallet to an address
- [ ] Poll for GET /erc20/transfer status and update UI if completed

![Image](https://user-images.githubusercontent.com/2378695/211558465-7f58cb2b-81fc-459a-a596-4eed25c4700c.png)
