### ISSUE TITLE
Store all claim objects in their own collection

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#330]
- [ ] Create ERC20PerkPayment and ERC721PerkPayment instead of Claim when `POST /v1/claims/:uuid/collect` is called
- [ ] Make sure that canClaim checks for both those objects to see if the claim already happened once
- [ ] Create migration for all claims and create ERC20PerkPayment and ERC721PerkPayment objects for every Claim in the collection
