### ISSUE TITLE
As a widget user I want to be able to claim a reward on a daily basis

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#360]
API
 - [x] Add new model `DailyReward: rewardBaseSchema & { amount, poolId }` and CRUD resource
 - [x] Add new model `DailyRewardClaim: { amount, sub }`
 - [x] Add `POST /rewards/daily/claim` and validate if `DailyRewardClaim.exists({sub, createdAt: Date.now() < 24h ago })`
 - [x] If validation ok then add points to point_balance of req.auth.sub
 - [x] Also create DailyRewardClaim again for this claim (this way it will be part of the next validation)

SDK
 - [x]  expose through SDK `client.rewards.daily.claim(sub)` 

Dashboard
- [x] Add "Daily" as first item in Rewards category of navbar
- [x] Add `daily-rewards` route
- [x] Provide view for daily-rewards route
- [x] View is similar to conditional rewards overview and modal (remove conditions component) 

Widget
- [x] Add a card similar to milestone rewards and remove progress bar (clean card)
- [x] For now just provide the claim button and lets come up with a nice UI experience for this one later
