### ISSUE TITLE
Implement milestone rewards for dashboard

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#361]
**API**
- [ ] Deploy your first pool (after pool deployment, only for pools.length == 1).
- [ ] Receive a your first claim for a referral reward in your pool `POST /rewards/:uuid/referral/claim` (after claim, claims.length = 1 and claim.poolId) 
- [ ] Receive a your first claim for a conditional reward in your pool `POST /rewards/:uuid/points/claim` (after claim, claims.length = 1 and claim.poolId) 
- [ ]  Receive a your first claim for a milestone reward in your pool `POST /rewards/:uuid/webhook/claim` (after claim, claims.length = 1 and claim.poolId) 

```typescript
const account = await AccountProxy.getById(pool.sub);
await axios({
        url: 'https://api.thx.network/v1/webhook/milestone/' + MILESTONETOKENS['pooldeployment'] + '/claim',
        method: 'POST',
        data: {
            address: account.address,
        },
});
    
```
