### ISSUE TITLE
Create POC Shopify Reward Conditions

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#380]
Configure Reward
- [x] in the account page implement the shopify connect button 
- [x] Add RewardConditionPlatform.Shopify
- [x] Add RewardConditionInteraction.Purchase, Subscribe, Review (review seems hard as it is not exposed by the API)
- [x] Add RewardCondition.content with a store ID retrieved after connecting through OAuth

Validate Purchase 
- [x] Introduce ShopifyService
- [x] Implement validatePurchase(email, amount);
- [x] Use these API methods

```typescript
// Get customer id for email address
await shopify.rest.Customer.search({
  session: session,
  query: "email:bob.norman@mail.example.com",
});

// Get orders for customer id
await shopify.rest.Customer.orders({
  session: session,
  id: 207119551,
});
```

**Comment by ghost** [comment]
@peterpolman unfortunately to perform the oauth we need to know the store url in advance.
Is it possible to save it somewhere perhaps in the account model?

**Comment by peterpolman** [comment]
If we need more info like this stored on for oauth purposes then we might want to create some generic OAuthConnection model containing the sub, tokens and potentially some metadata (like this store url). If you feel like integrating that right away then go for it, otherwise let's store it in account.

**Comment by ghost** [comment]
for this poc I will store it in the account, then if is everything  ok, we can create another ticket to use the OAuthConnection Model
