### ISSUE TITLE
As a widget user I want to redeem a lottery perk

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#442]
API 
- [ ] Check for erc721.variant in `GET /erc721/token` controller 
- [ ] In case of variant == ERC721Variant.Lottery 
- [ ] Query for all the LotteryPerkWinner objects where `erc721Id` is equal to `token.erc721Id`
- [ ] If there are winners take `winner[0].lotteryPerkId` and get the `LotteryPerk` info
- [ ] Sort LotteryPerkWinners for erc721Id on createdAt descending
- [ ] Limit the result for `perk.prizes.length`
- [ ] Add array of winners to the token response
- [ ] Add the perk to the token response

Widget
- [ ] For the response of `GET erc721/token` set the component based on the token.erc721.variant value
- [ ] Create a new component `BaseCardERC721Lottery`
- [ ] In the component show the list of winners.
