### ISSUE TITLE
As a dashboard user I want to earn THX referral and milestone rewards when integrating the widget

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#445]
This is meant for our sales ming initiative

Referral (dashboard signup)
- [x] Add ref from widget to the redirect to dashboard
- [x] Store ref in new account object
- [x] Add referral webhook URL as env var
- [x] Call webhook for account.ref when widget.domain === req.origin for `GET /widget/:id.js`
- [x] Add optional `metadata` field to referral webhook POST call
- [x] Add checkbox "Enable manual approval" for `referralReward.isManualApprovalEnabled`

Reward claimed
- [x] Add milestone webhook url as env var
- [x] Call webhook on conditional reward claim
- [x] Call webhook on daily reward claim
