### ISSUE TITLE
Create wallets in db for metamask users but do not deploy

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#452]
Improve wallet storage
- [x] Create migration for existing Metamask accounts
- [x] In migration create wallets for chainId Polygon with account.address as wallet address
- [x] When a user authenticates with Metamask for the first time also create a wallet in the database

Migrate Token sub to walletId
- [x] Create migration for all `ERC20Token`, `ERC721Token`, `ERC1155Token`, `Withdrawal`
- [x] In migration query wallet for token.sub and store `Wallet._id` in `Token.walletId`.
- [x] Assume query string param `chainId` for `GET /erc20/token` is always set
- [x] Get the Wallet for the authenticated sub
- [x] Instead of getting all tokens for a sub, now get all tokens for a walletId
- [x] Same thing for `GET /erc721/token` and `GET /erc1155/token`

**Comment by peterpolman** [comment]
@valeriagrazzini  Although we are lowering the prio on premium feature development I think this is still a good one to introduce as it would make working with wallets in the API more deterministic.
