### ISSUE TITLE
As a dashboard user I want to import ERC1155 contracts

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#457]
**Contracts**
- [x]  Create THX_ERC1155 contract for testing purposes
- [x]  Create ERC1155Facet contract for pool diamond to include
- [x]  Expose safeTransferFrom guarded for owner (relayer)
- [x]  Create tests for deploying THX_ERC1155, minting tokens to a pool diamond and transferring the tokens to a wallet

**API**
- [x] Create erc1155 resource (model, router, CRUD, test)

**AUTH**
- [x] Create erc1155 scopes to protect the resource

**Dashboard**
- [x] Add dropdown for erc721 or erc115 in the import modal
- [x] Based on selected call either `POST /erc721/import` or `POST /erc1155/import`
- [x] Use alchemy SDK to get tokens for pool address
- [x] Create ERC1155 object for imported contract
- [x] Create ERC1155Metadata for metadata found
- [x] Create ERC1155Token for tokens found
