### ISSUE TITLE
As a widget user I want to earn more points when claiming daily reward for consecutive days

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#499]
Dashboard
- [x] In DailyReward create modal add card component
- [x] In card component add an extendable list of "amount" values 
- [x] Store the values in `dailyReward.amounts: number[]` where index is the index of the consecutive day

Widget
- [x] Adjust DailyReward component progress bar to have a size of dailyReward.amounts.length
- [x] Make sure the count of consecutive DailyRewardClaims aligns with the % the bar is filled

API
- [x] Adjust existing `POST /daily-reward` controller for amounts storage
- [x] Adjust existing `GET /rewards` controller for dailyRewards
- [x] Respond with full amounts array
- [ ] Extend DailyRewardService with query for the amount of DailyRewardClaim.createdAt objects claimed in consecutive days (starting Date.now()) and return the count
- [x] Adjust existing `POST /rewards/daily/claim` controller to get the amount of points to claim based on the services query result.
- [x] Create migration for current dailyReward.amount ->  dailyReward.amounts where the array has a length of 7 and every value is the dailyReward.amount
