### ISSUE TITLE
As a widget user I want to answer a quiz and earn points

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#508]
```
SurveyRewardQuestion {
    surveyRewardId: String,
    question: String,
    answers: [{ correct: boolean, value: string }]
    createdAt: Date,
    updatedAt: Date,
}

SurveyReward {
  ...rewardBaseSchema,
  amount: Number,
  createdAt: Date,
  updatedAt: Date,
}

SurveyRewardAttempt {
   sub: String,
   surveyRewardId: String,
   result: Boolean,
   createdAt: Date,
   updatedAt: Date,
}

SurveyRewardClaim {
  sub: String,
  surveyRewardId: String,
  amount: Numbers,
  createdAt: Date,
  updatedAt: Date,
}
```

Auth
- [x] Introduce survey_reward:read and write scopes for new resource
- [x] Create migration for dashboard app (widget doesnt need any)

API
- [x] Introduce SurveyReward resource (LIST, GET, PATCH, POST, DELETE)
- [x] Extend /rewards with the SurveyReward type
- [x] Introduce POST /rewards/claim/survey-rewards and validate for
- [x] SurveyRewardAttempt.createdAt < 24h ago
- [x] SurveyRewardClaim should not exist for current sub

Dashboard
- [x] Introduce SurveyReward in dashboard navigation
- [x] Add table with all features for full CRUD
- [ ] In create model add component `BaseSurveyRewardQuestion` with field for `question` string
- [ ] In component add sub component `BaseSurveyRewardAnswer` with field for `value` string and `correct` boolean
- [ ] For both questions and answers add button to add another one
- [ ] On model submit run `POST /survey-rewards`

Widget
- [ ] Introduce `BaseCardSurveyReward` component
- [ ] In component show reward title and description as usual
- [ ] Add sub component `BaseSurveyRewardQuestion` showing the question and a submit button
- [ ] In question component show the first sub component `BaseSurveyRewardQuestion`
- [ ] On question submit show the next question 
- [ ] If all questions are answered run `POST /rewards/claim/survey-rewards` through SDK
- [ ] If response is 200 or 201 show "You have succesfuly completed this survey" success alert in the BaseCardSurveyReward component instead of the first question.
- [ ] If response is 403 show "Your answers were not correct" warning model
- [ ] Disable submit button for first question and show countdown timer based on the time of the last SurveyRewardAttempt.createdAt timestamp
