### ISSUE TITLE
As a widget user I want to see a stored preview of the tweet i need to retweet or like

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#518]
![Image](https://user-images.githubusercontent.com/2378695/226652969-63f78874-a250-456f-bf30-2ca19423e81c.png)

Dashboard
- [x] In POST and PATCH /point-rewards requests add `contentMetadata` property
- [x] `contentMetadata` should JSON.stringify({ tweetUrl, twitterUsername, tweetContent })

API
- [x] Extend POST and PATCH /point-rewards with contentMetadata property
- [x] Add `contentMetadata` to PointReward model and interfaces
- [x] In GET /rewards als return contentMetadata for the conditional rewards

Widget
- [x] Introduce new `BaseBlockquoteTweetPreview` component
- [x] Use it for both the Retweet and Like Twitter rewards
