### ISSUE TITLE
As a widget user I want to be able to subscribe for reward notifications

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#519]
API 
- [x] Add new model "PoolSubscription" { sub, poolId }
- [x] Add `POST /pools/:id/subscription` where PoolSubscription is created for `req.auth.sub`
- [x] In this controller also run `AccountProxy.update()` for the email if it is not available for the authenticated user
- [x] Add `DELETE /pools/:id/subscription` where PoolSubscription is deleted for `req.auth.sub`
- [x] Add `GET /pools/:id/subscription` which returns the PoolSubscription object or null
- [x] Add job "sendPoolNotifications"
- [x] Trigger an instance of the job on `PointRewardService.create()` with arguments { poolId, rewardId }
- [x] In job query the `PoolSubscriptions` for `job.params.poolId` and create batcher of max 600
- [x] With a delay of 1 minute Promise.all() the email requests for the batch

SDK
- [x] Add `sdk.poolManager.subscription.post(poolId)`

Widget
- [ ] On init request `GET /pools/:id/subscription`
- [ ] Add bell icon in widget header
```
<i class="fas fa-bell"></i> Is subscribed
<i class="fas fa-bell-slash"></i> Is not subscribed
```
- [ ] When clicked open modal
- [ ] In modal show disabled text input with account.email
- [ ] If `account.email` is not set do not disable the field
- [x] If user is not subscribed show "Subscribe" and call `POST /pools/:id/subscription`
- [x] If user is subscribed show "Unsubscribe" and call `DELETE /pools/:id/subscription`

```
Hi!

You can earn {{ reward.amount }} points in pool [pool.title](widget.domain) for the new reward: 
**{{ reward.title }}**.
```
