### ISSUE TITLE
As a discord bot user I want to display the leaderboard

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#523]
Auth
- [x] Add `pool_analytics:read` scope
- [x] Create migration for client_name "THX Discord" and add `pool_analytics:read` scope

API
- [x] Add a separate controller for `GET /pools/:poolld/analytics/leaderboard/client` guarded with `pool_analytics:read` scope
- [x] Add `getLoaderboard(poolId)` to poolManager and request `GET /pools/:poold/analytics/leaderboard/client`

Discord
- [x] Add support for `/thx leaderboard`
- [x] Run `sdk.poolManager.getLoaderboard(Guild.poolId);`
- [x] Display the list like this:

```
1. 250 | Valeria 0x12345...
2. 200 | @peterpolman 0x23456...
3. 150 | 0x34567...
```
