### ISSUE TITLE
As a dashboard user I want to configure conditional rewards for successful discord invites

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#545]
https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/tracking-used-invites.md

Discord Bot
- [ ] Verify that the correct scopes for obtaining `GuildMemberAdd` and `InviteCreate` events are requested
- [ ] Create `gatewayevents` collection with `GatewayEvent { guildId, name, event }`
- [ ] In event handlers GuildMemberAdd store the event in the database
- [ ] In event handlers InviteCreated store the event in the database
- [ ] Implement invite caching as in the mentioned source but store the Invites cache in the database instead of memory
