### ISSUE TITLE
As a widget user I want to claim a reward for the amount of used invite links I created in a server

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#548]
Discord HTTP
- [x] Implement express and configure graphql-apollo-server
- [x] Add endpoint to query for at least "invites used per discord user"
https://medium.com/geekculture/graphql-with-mongodb-and-expressjs-26e1b94ab886

Dashboard
- [x] Add DiscordInviteUsed interaction to the reward conditions enum
- [x] Provide number input field for threshold (indicating the amount of used invite links for a discord user)

API
- [x] Extend validateCondition logic with new interaction type
- [x] Introduce new DiscordBotService 
- [x] Query DiscordBot API for the "invites used per discord user"
- [x] If the result exceeds or is equal to the threshold return true for validation 

Widget
- [x] Implement proper preview blockquote for this reward condition type
