### ISSUE TITLE
As a dashboard user I want to set a hashtag for tweets that should become rewards

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#551]
Dashboard
- [ ] Add hashtag text input in campaign settings for Automated Twitter rewards
- [ ] Add value to PATCH /pools

API
- [ ] Extend PATCH /pools to receive `settings.defaults.conditionalRewards.hashtag`
- [ ] Extend AssetPool model for new setting
- [ ] In `createConditionalRewards` job check the tweet for containing the hashtag if a hashtag is set in pool settings
