### ISSUE TITLE
As a widget user I want to claim daily rewards based on webhook calls

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#555]
Dashboard
- [x] Introduce checkbox in DailyReward claim modal "Enable webhook qualification"
- [x] Show webhook qualification card similar to milestone rewards model
- [x] Extend POST request with isEnabledWebhookQualification boolean

API
- [x] Extend DailyReward model with `isEnabledWebhookQualification` boolean
- [x] Extend DailyRewardClaim model with state property (Number)
- [x] Introduce enum `DailyRewardClaimState { Pending = 0, Claimed = 1}`
- [x] Introduce `POST /webhooks/daily`
- [x] In controller create DailyRewardClaim object with state = DailyRewardClaimState.Pending
- [x] In `POST /rewards/daily/claim` extend DailyRewardClaim validation to return true if
- [x] None exist within the timeframe OR and IF (reward.isEnabledWebhookQualification)
- [x] DailyRewardClaim exists but with state = DailyRewardClaimState.Pending
- [x] After validation either create the new DailyRewardClaim or update the existing one with state = DailyRewardClaimState.Claimed
