### ISSUE TITLE
As a widget user I want to see a model that the campaign expired after campaign expiration

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#559]
Dashboard 
- [ ] Rename pools to campaigns everywhere visible in the UI
- [ ] Add endDate date field to pool create/edit modal

API
- [ ] Extend Pool model with endDate property
- [ ] In POST /pools do not set the endDate
- [ ] In GET /widget/:id also check if endDate > now and store `expired` boolean in the settings object
- [ ] On widget inject pass the `expired` in the url of the iframe

Widget
- [ ] Check in Points and Perks view detect if `expired` is true show a new modal component
- [ ] Modal component BaseModalCampaignExpired should say "This campaign has ended."
- [ ] Disable close functionality for modal
- [ ] User should still be able to visit Wallet view
