### ISSUE TITLE
As a dashboard user I want to create custom webhook perks

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#574]
/Dashboard
- [x] Add input for webhook URL in Dashboard -> Developer -> Events
- [x] Add view controller for page and POST/PATCH the pool with the `eventWebhookURL` data
- [x] Add input readonly and copy for webhook signing secret
- [x] Extend Dashboard analytics to show CustomRewardClaims

API (Analytics)
- [x] Extend analytics to include CustomRewardClaim

API (Webhook Secret)
- [x] Generate `pool.settings.eventWebhookSecret` upon pool creation
- [x] Create migration for existing pools

API (Event Webhook)
- [x] Add pool.settings.eventWebhookURL field
- [x] Adjust `POST and PATCH /pool/:id endpoints to store data`
- [x] Sanitize inputs

API (Custom Rewards)
- [x] Add `POST, PATCH, GET, GET (list) /custom-reward/:id` endpoints { title, description, }
- [x] Add tests for custom rewards
- [x] Add `POST /perks/custom/redeem` endpoint
- [x] Do regular validation
- [x] Sign payload with `pool.settings.eventWebhookSecret`
- [x] Run `pool.settings.eventWebhookURL`
- [x] Catch error if so and on 200 do point subtraction
- [x] Extend SDK with new `POST /perks/custom//redeem` endpoint
- [x] Extend SDK with a client method for event construction
```javascript
stripe.webhooks.constructEvent(
        request.body,
        signature: request.headers['X-Webhook-Signature'],
        endpointSecret
);
```
Widget
- [x] Add CustomReward card
- [x] Extend store methods for custom reward listing
- [x] Extend store methods for custom reward redemption
- [x] Add CustomRewardClaim card to show on /wallet

**Comment by peterpolman** [comment]
Prospect seems eager for this. Increase prio.
