### ISSUE TITLE
As an SDK user I want to programmaically invite my user for a wallet

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#601]
- [x] Client runs `POST /webhook/milestone/:token` for `user.walletId`
- [x] THX API returns
```
{
 // claim info
 // wallet info
}
```
- [x] Alice visits `walletURL` https://example.com/?thx_widget_path=/w/:token
- [x] THX Widget shows WalletCollect view “This wallet contains 535 points, continue to claim ownership.”
- [x] Alice clicks Continue and THX Widget redirects Alice to THX Auth with param `:token`
