### ISSUE TITLE
As a widget user I want to claim ownership of a wallet

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#602]
Auth
- [x] Alice chooses a sign-in method
- [x] THX Auth authenticates Alice and creates a new account
- [x] THX Auth runs `WalletProxy.getTransfer(wallet_transfer_token)`
- [x] --THX API sets `sub` for existing wallet._id for the wallet without `poolId`--
- [x] THX Auth redirects to widget

Info
- [x] THX API GET /wallets should also return point balances per wallet

Transfer
- [x] THX Widget requests THX API `PATCH /account/wallet` for `:token`
- [x] THX API updates all existing reward claims for the new wallet with the already existing wallet._id
- [x] THX API set property `wallet.primaryWalletId = wallet._id`  
- [x] All subsequent milestone reward webhook calls for oldWallet._id will return the primary wallet (wallet with address)
- [x] All subsequent milestone reward webhook calls for oldWallet._id will add claims and points for the primary wallet
