### ISSUE TITLE
As a dashboard user I want to configure different button styles for bottom navigation

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#608]

**Comment by peterpolman** [comment]
- [x] Make uuid the only way to access a wallet from the clients perspective 
- [x] Complete test coverage for wallet onboarding
- [x] Run staging tests
- [x] Verify what happens if a new user shows up that claims an onboarded wallet, but does not have a deployed wallet yet
