### ISSUE TITLE
Research ERC-4337 Account Abstraction

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#623]
## Goal
Find a solution to make our current smart wallet architecture self-custodial in order to not be the subject to current wallet custody regulation.

## Sources
- [Conceptual overview](https://metamask.io/news/latest/account-abstraction-past-present-future/)
- [Implementation walkthrough](https://www.alchemy.com/blog/account-abstraction)
- [ERC-4337](https://eips.ethereum.org/EIPS/eip-4337)
- [Implementation reference](https://github.com/eth-infinitism/account-abstraction/tree/main/contracts)
- [Relation to MPC](https://zengo.com/aa-and-mpc-frens-with-benefits/)
- [Web3Auth TSS SDK](https://web3auth.io/docs/sdk/tkey/) (MPC toolkit)

## Required
- [x] Self-Custodial
- [x] Key Recovery (forces the use of MPC key management)
- [x] Relayed Gas Payments
- [x] Hardhat support (Shanghai hardfork)
- [x] Web3JS support (soft)

## Implementation
A combination of ERC-4337 (Account Abstraction) based Smart Wallets and an MPC account to sign UserOperations will achieve our goal.

### Smart Wallet
This contract functions as a self-custodial smart contract wallet delegating gas fee payments to a Paymaster contract. The Company will be responsible for making sufficient MATIC deposits to the Paymaster contract.

UserOperations will be execute by executeOp and requires signatures from 2 EOA's.

- Signature 1: Company Controlled Signing Key
- Signature 2: User Controlled Signing Key (MPC)

### MPC Wallet
An off-chain MPC wallet will provide a self-custodial key management solution where the company only has access to 1 out of 3 key shares. 

- Share 1: Device (Encrypted Local Storage)
- Share 2: Social (Any OAuth server)
- Share 3: Backup (Delegated social connection)

When creating a `UserOperation` and calling `executeOp` the ERC-4337 smart wallet 2 out of 3 are required to sign the UserOperation.

![Image](https://github.com/thxprotocol/monorepo/assets/2378695/14e409bd-09a1-4e46-868f-b62de6f33e61)
