### ISSUE TITLE
Implement ERC-4337 in smart wallets

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#628]
https://docs.safe.global/learn/safe-core/safe-core-account-abstraction-sdk/protocol-kit

**Comment by peterpolman** [comment]
Wallet
- [ ] Widget ERC20 Transfer
- [ ] Widget ERC721 Transfer
- [ ] Widget ERC1155 Transfer

Campaign
- [ ] Campaign ERC20 Transfer
- [ ] Campaign ERC721 Transfer
- [ ] Campaign ERC1155 Transfer
- [ ] Campaign ERC721 Mint
- [ ] Campaign ERC1155 Mint
- [ ] Campaign ERC20 AddMinter
- [ ] Campaign ERC721 AddMinter
- [ ] Campaign ERC1155 AddMinter

**Comment by peterpolman** [comment]
Finished SafeSDK Wallet implementation
