### ISSUE TITLE
As a user I want to create metadata in bulk based on uploaded image files

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#66]
Dashboard should allow for uploading multiple files at once and prepare metadata for the uploaded files.

Dashboard:
- [ ] Add button to overview "+ Upload images"
- [ ] Show modal with form and these fields
- [ ] Add select box for available erc721 properties of the propType "image"
- [ ] Add field for uploading multiple files (use default browser UI)
- [ ] On submit request the API `POST /erc721/metadata/multiple`
- [ ] After request success call `GET /erc721/metadata` to refresh the list

API 
- [ ] Introduce `POST /erc721/metadata/multiple` endpoint
- [ ] Upload the files to the public s3 bucket
- [ ] Create a metadata object for every file uploaded
- [ ] Push `{ key: req.body.propName, value: s3Url }` on the `metadata.attributes[]` array
- [ ] Respond with the created metadata object
