### ISSUE TITLE
Download CSV file for available metadata of erc721

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#68]
Dashboard:
- [ ] Add button to overview "+ Upload spreadsheet"
- [ ] In modal shown download link for CSV
- [ ] On clicking the download link download the CSV through the API

API:
- [ ] Add endpoint `GET /erc721/:id/metadata/csv` to download a CSV file
- [ ] If a CSV already exists delete it before creating the new one (or replace it if possible)
- [ ] Create CSV with one row of comma separated property names + the id of the metadata object
- [ ] Add rows for all the existing metadata for this erc721
- [ ] Create the CSV file and upload to private s3 bucket
- [ ] On upload success respond with a readStream of the uploaded file
