### ISSUE TITLE
Bulk metadata creation/update based on uploaded csv (sheet)

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#69]
**Dashboard**
- [ ] Add button "Upload CSV"
- [ ] Open modal with file input field
- [ ] On submit make request to `POST /erc721/:id/metadata`

**API**
- [ ] Rename `POST /erc721/:id/metadata/images`
- [ ] Add route `POST /erc721/:id/metadata/csv`
- [ ] Rename existing `POST /erc721/:id/metadata to POST /erc721/:id/metadata/single`
- [ ] Add route `POST /erc721/:id/metadata` with special middleware utilizing e.g. `route('/erc721/:id/metadata/csv')` to forward the request to a different controller based on the payload type (body: json, file: zip, file: csv)
- [ ] Add controller for csv child endpoint
- [ ] Pick CSV parser and parse the csv file into an object or array
- [ ] Iterate over the rows
- [ ] If an id is present, update the provided metadata properties
- [ ] If an id is not present, insert the provided metadata properties into a new object
- [ ] If all is good, respond with a 200
- [ ] Add tests
- [ ] Check performance
