### ISSUE TITLE
Add paging to rewards overview

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#70]
Dashboard
- [ ] Implement paging approach as found in clients overview for rewards

API
- [ ] Add paging query string parameters GET /rewards endpoint
- [ ] Fix the tests since they will break when calling /rewards

**Comment by GarfDev** [comment]
Closing this with https://github.com/thxprotocol/dashboard/pull/92
@peterpolman
