### ISSUE TITLE
Add paging to metadata overview

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#71]
**Dashboard**
- [ ] Show pagination component for metadata overview
- [ ] Display a 100 metadata entries per page

**API**
- [ ] Extend GET /erc721/:id/metadata endpoints with filter parameters for paging
- [ ] Paginate the actual response of the controller
- [ ] Adjust the tests
