### ISSUE TITLE
Contract Verification

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#736]
- [ ] Get polygonscan key
- [ ] Create migration for verifications of contracts in accounts with a paid plan
- [ ] Extend deploy methods for contracts with verification 
- [ ] Only do for paid plans 

```typescript
const { ethers } = require('ethers');
const Web3 = require('web3');
const fs = require('fs');

// Replace these values with your actual ones
const infuraApiKey = 'your-infura-api-key';
const etherscanApiKey = 'your-etherscan-api-key';
const contractAddress = '0xYourContractAddress';
const deployerAddress = '0xYourDeployerAddress';
const deployerPrivateKey = '0xYourPrivateKey';

// Connect to an Ethereum node (Infura)
const provider = new ethers.providers.JsonRpcProvider(`https://mainnet.infura.io/v3/${infuraApiKey}`);

// Use Web3 to obtain the deployment transaction hash
const web3 = new Web3(`https://mainnet.infura.io/v3/${infuraApiKey}`);
web3.eth.getTransactionReceipt(contractAddress, async (error, receipt) => {
  if (!error) {
    const transactionHash = receipt.transactionHash;

    // Read the compiled Solidity contract (output of the compilation)
    const compiledContract = fs.readFileSync('path/to/compiledContract.json');
    const compiledContractJSON = JSON.parse(compiledContract);

    // Get the contract's ABI and bytecode from the compiled JSON
    const abi = compiledContractJSON.abi;
    const bytecode = compiledContractJSON.bytecode;

    // Create a wallet using the deployer's private key
    const wallet = new ethers.Wallet(deployerPrivateKey, provider);

    // Verify the contract on Etherscan
    const verification = await ethers.utils.verifyContract(
      transactionHash,
      abi,
      bytecode,
      deployerAddress,
      etherscanApiKey
    );

    console.log('Contract verified:', verification);
  } else {
    console.error('Error getting transaction receipt:', error);
  }
});
```
