### ISSUE TITLE
POC: Implement eternal storage provider

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#88]
- [ ] Look into https://github.com/thxprotocol/api/pull/345/files
 - [ ] Create a similar setup based on the most recent API codebase
 - [ ] Introduce env variable `ARWEAEVE_ENABLED` for this feature
 - [ ] When uploading NFT images, check `ARWEAEVE_ENABLED` and upload to Arweave instead of the AWS bucket if true
