### ISSUE TITLE
As as dashboard user I want to download a zip with unique QR codes for every metadata item in my collection

### ISSUE THREAD

**Issue by peterpolman** [thxprotocol/monorepo-legacy#96]
**API**
- [ ] Extend `POST /erc721/:id/metadata/csv` and
- [ ] Extend `POST /erc721/:id/metadata/zip`
- [ ] Create a Reward for every piece of ERC721Metadata created
- [ ] Create 1 claim for every Reward created
- [ ] Add endpoint to download a zip with QR codes for all these the metadata rewards in the collection

**Dashboard**
- [ ] Add dropdown to metadata overview
- [ ] Add all existing buttons to the dropdown
- [ ] Add new button "Download QR codes" 
- [ ] On click request the API for a download of a zip with QR codes for all the metadata in the collection

**Comment by ghost** [comment]
created branch: metadata-qrcodes
question: since the reward creation needs some fields to be filled by the customer: (reward conditions, expiration, reward title, ecc..). How do we handle that part?

**Comment by peterpolman** [comment]
@valeriagrazzini All those fields should be left undefined since "owning" the QR should be the only condition for claiming the NFT.

**Comment by ghost** [comment]
@peterpolman I have created the PR but I think that there is a "BUG" in the vuejs's file input.
Example: I upload 2 files from a directory and submit, then the second time I upload other 3 files and submit again, the API receives 3+2 files instead of 3. The previous 2 files remain in vue's memory

**Comment by peterpolman** [comment]
@valeriagrazzini Maybe try to reference the HTML input element and reset it like this:
https://bootstrap-vue.org/docs/components/form-file#clearing-the-file-selection
